apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdbscan-jm-workerpvc
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
